TebLocalPlannerROS:

  odom_topic: odom
  map_frame: /map

  # Trajectory
  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1

  # Robot
  max_vel_x: 0.4
  max_vel_x_backwards: 0.2
  max_vel_y: 0.2
  max_vel_theta: 0.5
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  acc_lim_theta: 0.5

  # Mecanum configuration
  min_turning_radius: 0.0
  wheelbase: 0.0
  weight_kinematics_nh: 1 # 全向移动支持

  # GoalTolerance
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.2
  free_goal_vel: False

  # Obstacles
  min_obstacle_dist: 0.25
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False

  weight_max_vel_x: 2
  weight_max_vel_y: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_y: 1
  weight_acc_lim_theta: 1
  weight_kinematics_forward_drive: 1
  weight_obstacle: 50
